### ISSUE TITLE
online repository 404 - not found

### ISSUE THREAD

**Issue by chenbekor** [ReactiveCouchbase/ReactiveCouchbase-core#69]
https://raw.githubusercontent.com/ReactiveCouchbase/repository/master/snapshots

is not available - can you please check?

**Comment by mathieuancelin** [comment]
Hi Chen,

that's weird because, I can access this URL without any issue

https://raw.githubusercontent.com/ReactiveCouchbase/repository/master/snapshots/org/reactivecouchbase/reactivecouchbase-core_2.11/0.4-SNAPSHOT/reactivecouchbase-core_2.11-0.4-SNAPSHOT-javadoc.jar.sha1

So I guess I should world for any other file right ?

**Comment by chenbekor** [comment]
the assets are accessible - but building a clean project (play) causes sbt to timeout while trying to resolve reactivecouchbase dependencies. can you please try creating a new play app sbt play-scala-2.3  activator template? please use latest activator

**Comment by mathieuancelin** [comment]
Hi Chen,

I just created a new play-scala-2.3 project with activator 1.3.5, added reactive couchebase 0.4, emptied my Ivy repo and compiled the project.

And it worked great.

Maybe your Ivy repo is in bad shape ?

**Comment by chenbekor** [comment]
could be - will test tomorrow. 10x Mathieu!!
